### ISSUE TITLE
mouse not work

### ISSUE THREAD

**Issue by ayoubelmhamdi** [yazgoo/vmux#29]
when I switch using prefix: `<C-G>`, the mouse not work, I should:
```vim
:set mouse=
:set mouse=a
```
every time I use `prefix`

**Comment by yazgoo** [comment]
from my tests, the mouse works the first time you setup the session, then it does not on following sessions
to me it means that either of those  screws up mouse support :
- skim selector printing
- diss cleanup
not yet indentified which one though

**Comment by yazgoo** [comment]
should be fixed by https://github.com/yazgoo/vmux/commit/bb6d84ce7d708222fa718deb05b49a0347f5baed

Please reinstall vmux and tell me if it fixes it on your end

**Comment by yazgoo** [comment]
please reopen if it is not fixed
